spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hipstercard-db
    username: hipstercard-db-user
    password: hipstercard-db-password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true
  application:
    name: transactions-service
  liquibase:
    change-log: classpath:/db/changelog.xml

server:
  port: 8081
