spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true

  application:
    name: transactions-service

server:
  port: 8081

#eureka:
#  client:
#    preferIpAddress: true
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone:
#        http://localhost:8070/eureka/

